[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[tool.setuptools.packages]
find = {} 

[project]
name = "kLogs-util"
version = "0.3.0"
readme = {file = "README.md", content-type = "text/markdown"}
keywords = ["log", "logging"]
authors = [
    {name = "Kevin J. Mahon", email = "k.mahon.dev@gmail.com"}
]
description = "Lightweight logging utility for python. Wrapper around stdlib"
requires-python = ">=3.10"
dependencies=[
    "executing",
    "asttokens",
]
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/kevin-mahon/kLogs/tree/main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
    "ty>=0.0.75",
]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests/unit", "tests/integration"]

